import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'h-screen flex border-black max-w-screen-md m-auto p-4 text-xl leading-8 md:text-base')}>
        {children}
        <footer>
          {/* TODO: add credit to the book */}
        </footer>
      </body>
    </html>
  );
}
