import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'h-dvh overflow-hidden m-auto relative max-w-screen-md text-xl leading-8 md:text-base')}>
        <div className="flex flex-col px-4 h-full overflow-y-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
